### ISSUE TITLE
[DOWNLOADS]

### ISSUE THREAD

**Issue by RobotZguy** [Mathias-Boulay/Android-Game-Booster#4]
Hey there, the downloads are not available. I checked in packages but there's nothing there. What's the use of making an app which can't be even downloaded properly. This will make it hard for some users, maybe you can make a video about how to do the installation process.

**Comment by Mathias-Boulay** [comment]
> Hey there, the downloads are not available. I checked in packages but there's nothing there. What's the use of making an app which can't be even downloaded properly. This will make it hard for some users, maybe you can make a video about how to do the installation process.

The installation process is simple: compile it.

**Comment by Mathias-Boulay** [comment]
also #1
